# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MrWriter
author: Thomas Leitz
email: thomas.leitz@web.de
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mrwriter.org" # the base hostname & protocol for your site
twitter_username: unruhschuh
github_username:  unruhschuh

# Build settings
markdown: kramdown
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

gems:
  - jekyll-asciidoc
